# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Beispieltitel', max_length=200, verbose_name=b'Titel')),
                ('document', models.FileField(upload_to=b'documents', verbose_name=b'Dokument')),
                ('description', models.CharField(max_length=400, verbose_name=b'Beschreibung')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(upload_to=b'downloads', verbose_name=b'Datei')),
                ('name', models.CharField(max_length=200, verbose_name=b'Titel')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default=b'Beispieltitel', max_length=200, verbose_name=b'Titel')),
                ('link', models.CharField(default=b'http://example.ch', max_length=200, verbose_name=b'Link')),
                ('description', models.CharField(max_length=400, verbose_name=b'Beschreibung')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(upload_to=b'medias', verbose_name=b'Datei')),
                ('name', models.CharField(max_length=200, verbose_name=b'Titel')),
                ('year', models.CharField(max_length=4, verbose_name=b'Jahr')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medien',
            },
        ),
        migrations.CreateModel(
            name='Politoloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name=b'E-Mail Adresse')),
            ],
            options={
                'permissions': (('can_send_newsletter', 'Kann politoloco-Newsletter verschicken'),),
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Waehle eines der folgenden Werte: <ul><li>"my.ortoloco" - Ankuendigungen auf my.ortoloco</li><li>"Willkommen" - ortolco - Homepage oben rechts</li><li>"HomeUnterMenu" - ortoloco-Homepage unten unterm Menu', max_length=100, verbose_name=b'Name')),
                ('content', tinymce.models.HTMLField(default=b'', max_length=10000, verbose_name=b'Html-Inhalt')),
            ],
            options={
                'verbose_name': 'Statischer Inhalt',
                'verbose_name_plural': 'Statische Inhalte',
            },
        ),
    ]
