# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_ortoloco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name=b'Nummer zum Sortieren'),
        ),
        migrations.AddField(
            model_name='download',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name=b'Nummer zum Sortieren'),
        ),
        migrations.AddField(
            model_name='link',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name=b'Nummer zum Sortieren'),
        ),
    ]
