# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juntagrico.util.temporal
import re


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarea',
            name='core',
            field=models.BooleanField(default=False, verbose_name='Kernbereich'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='versteckt'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='show_coordinator_phonenumber',
            field=models.BooleanField(default=False, verbose_name='Koordinator Tel Nr Veröffentlichen'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='core_cache',
            field=models.BooleanField(default=False, verbose_name='Kernbereich'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungssdatum'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='bezahlt'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ref_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Referenznummer'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='addr_location',
            field=models.CharField(max_length=50, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='addr_street',
            field=models.CharField(max_length=100, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='addr_zipcode',
            field=models.CharField(max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='latitude',
            field=models.CharField(default='', max_length=100, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='longitude',
            field=models.CharField(default='', max_length=100, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Depot Name'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='weekday',
            field=models.PositiveIntegerField(choices=[(1, 'Montag'), (2, 'Dienstag'), (3, 'Mittwoch'), (4, 'Donnerstag'), (5, 'Freitag'), (6, 'Samstag'), (7, 'Sonntag')], verbose_name='Wochentag'),
        ),
        migrations.AlterField(
            model_name='extrasubscription',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungssdatum'),
        ),
        migrations.AlterField(
            model_name='extrasubscription',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='gekündigt'),
        ),
        migrations.AlterField(
            model_name='extrasubscription',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivierungssdatum'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptioncategory',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptioncategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptioncategory',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name='Nummer zum Sortieren'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptiontype',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptiontype',
            name='size',
            field=models.CharField(default='', max_length=100, verbose_name='Groesse (gross,4, ...)'),
        ),
        migrations.AlterField(
            model_name='extrasubscriptiontype',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name='Groesse zum Sortieren'),
        ),
        migrations.AlterField(
            model_name='job',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='abgesagt'),
        ),
        migrations.AlterField(
            model_name='job',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder verschickt'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.PositiveIntegerField(verbose_name='Plaetze'),
        ),
        migrations.AlterField(
            model_name='jobextra',
            name='per_member',
            field=models.BooleanField(default=False, verbose_name='jeder kann Extra auswählen'),
        ),
        migrations.AlterField(
            model_name='jobextratype',
            name='display_empty',
            field=models.CharField(max_length=1000, verbose_name='Icon für felhlendes Extra'),
        ),
        migrations.AlterField(
            model_name='jobextratype',
            name='display_full',
            field=models.CharField(max_length=1000, verbose_name='Icon für Extra'),
        ),
        migrations.AlterField(
            model_name='jobextratype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='displayed_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Angezeigter Name'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='code',
            field=models.TextField(default='', max_length=1000, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='template',
            field=models.TextField(default='', max_length=1000, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr_location',
            field=models.CharField(max_length=50, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr_street',
            field=models.CharField(max_length=100, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr_zipcode',
            field=models.CharField(max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='member',
            name='block_emails',
            field=models.BooleanField(default=False, verbose_name='keine emails'),
        ),
        migrations.AlterField(
            model_name='member',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='bestätigt'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefonnr'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reachable_by_email',
            field=models.BooleanField(default=False, verbose_name='Kontaktierbar von der Job Seite aus'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='displayed_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Angezeigter Name'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bezahldatum'),
        ),
        migrations.AlterField(
            model_name='share',
            name='booking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eingebucht am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gekündigt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ausgestellt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='share',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anteilschein Nummer'),
        ),
        migrations.AlterField(
            model_name='share',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bezahlt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='payback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zurückbezahlt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gekündigt auf'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungssdatum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Erstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivierungssdatum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='future_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Zukuenftige Groesse'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=juntagrico.util.temporal.start_of_next_business_year, verbose_name='Gewünschtes Startdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='depot_list',
            field=models.BooleanField(default=True, verbose_name='Sichtbar auf Depotliste'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='long_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Langer Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='required_assignments',
            field=models.PositiveIntegerField(verbose_name='Anz benötigter Arbeitseinsätze'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='shares',
            field=models.PositiveIntegerField(verbose_name='Anz benötigter Anteilsscheine'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='size',
            field=models.PositiveIntegerField(unique=True, verbose_name='Grösse'),
        ),
    ]
