# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0002_auto_20170421_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSubBillingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Preis')),
                ('start_day', models.PositiveIntegerField(verbose_name='Start Tag')),
                ('start_month', models.PositiveIntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], verbose_name='Start Monat')),
                ('end_day', models.PositiveIntegerField(verbose_name='End Tag')),
                ('end_month', models.PositiveIntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], verbose_name='End Monat')),
                ('code', models.TextField(default='', max_length=1000, verbose_name='Code für Teilabrechnung')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='juntagrico.ExtraSubscriptionType')),
            ],
            options={
                'verbose_name': 'Verechnungsperdiode Zusatzabos',
                'verbose_name_plural': 'Verechnungsperdioden Zusatzabos',
            },
        ),
        migrations.AddField(
            model_name='subscriptionsize',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Preis'),
            preserve_default=False,
        ),
    ]
