# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0004_auto_20171017_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(
                blank=True, max_length=1000, verbose_name='Notizen'),
        ),
    ]
