# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0005_subscription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasubbillingperiod',
            name='cancel_day',
            field=models.PositiveIntegerField(default=1, verbose_name='Kündigungs Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrasubbillingperiod',
            name='cancel_month',
            field=models.PositiveIntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], default=1, verbose_name='Kündigungs Monat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='gekündigt'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Gewünschtes Enddatum'),
        ),
    ]
