# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0006_loco_block_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteilschein',
            name='canceled_date',
            field=models.DateField(null=True, verbose_name=b'Canceled am'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='notes',
            field=models.TextField(default=b'', max_length=1000, verbose_name=b'Notizen'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='number',
            field=models.IntegerField(null=True, verbose_name=b'Anteilschein nummer'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='paid_date',
            field=models.DateField(null=True, verbose_name=b'Bezahlt am'),
        ),
    ]
