# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0006_auto_20171102_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasubbillingperiod',
            name='price',
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name='Preis'),
        ),
    ]
