# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0006_auto_20171025_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kündigüngssdatum'),
        ),
        migrations.AlterField(
            model_name='extrasubbillingperiod',
            name='code',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Code für Teilabrechnung'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gewünschtes Enddatum'),
        ),
    ]
