# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0007_auto_20160618_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAboCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Name')),
                ('description', models.TextField(max_length=1000, verbose_name=b'Beschreibung')),
                ('sort_order', models.FloatField(default=1.0, verbose_name=b'Nummer zum Sortieren')),
            ],
            options={
                'verbose_name': 'Zusatz-Abo-Kategorie',
                'verbose_name_plural': 'Zusatz-Abo-Kategorien',
            },
        ),
        migrations.AddField(
            model_name='extraabotype',
            name='size',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'Groesse (gross,4, ...)'),
        ),
        migrations.AddField(
            model_name='extraabotype',
            name='sort_order',
            field=models.FloatField(default=1.0, verbose_name=b'Groesse zum Sortieren'),
        ),
        migrations.AlterField(
            model_name='anteilschein',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Canceled am'),
        ),
        migrations.AlterField(
            model_name='anteilschein',
            name='notes',
            field=models.TextField(blank=True, default=b'', max_length=1000, verbose_name=b'Notizen'),
        ),
        migrations.AlterField(
            model_name='anteilschein',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Anteilschein Nummer'),
        ),
        migrations.AlterField(
            model_name='anteilschein',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Bezahlt am'),
        ),
        migrations.AlterField(
            model_name='loco',
            name='reachable_by_email',
            field=models.BooleanField(default=False, verbose_name=b'Kontaktierbar von der Job Seite aus'),
        ),
        migrations.AddField(
            model_name='extraabotype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='my_ortoloco.ExtraAboCategory'),
        ),
    ]
