# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0007_auto_20171030_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'permissions': (('can_load_templates', 'Benutzer kann Templates laden'),), 'verbose_name': 'MailTemplate', 'verbose_name_plural': 'MailTemplates'},
        ),
    ]
