# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0008_auto_20160724_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_operations_group', 'Benutzer ist in der BG'), ('is_book_keeper', 'Benutzer ist Buchhalter')),
            },
        ),
        migrations.AlterField(
            model_name='extraabocategory',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name=b'Beschreibung'),
        ),
    ]
