# Generated by Django 2.0.2 on 2018-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0010_auto_20180210_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Arbeitseinsatz',
                     'verbose_name_plural': 'Arbeitseinsätze'},
        ),
        migrations.AlterModelOptions(
            name='billable',
            options={'verbose_name': 'Verrechenbare Einheit',
                     'verbose_name_plural': 'Verrechenbare Einheiten'},
        ),
        migrations.AlterField(
            model_name='member',
            name='iban',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='IBAN'),
        ),
    ]
