# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0010_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='abo',
            name='future_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_abo_set', to='my_ortoloco.Depot'),
        ),
        migrations.AlterField(
            model_name='abo',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abo_set', to='my_ortoloco.Depot'),
        ),
    ]
