# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:21
from __future__ import unicode_literals

from django.db import migrations

def fill_boehnli_core_cache(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Boehnli = apps.get_model("my_ortoloco", "Boehnli")
    for boehnli in Boehnli.objects.all():
        boehnli.save()

class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0012_boehnli_core_cache'),
    ]

    operations = [
        migrations.RunPython(fill_boehnli_core_cache),
    ]
