# Generated by Django 2.0.2 on 2018-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0013_auto_20180807_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMessage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(
                    max_length=256, verbose_name='Nachricht')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('sort_order', models.FloatField(
                    default=1.0, verbose_name='Nummer zum Sortieren')),
            ],
            options={
                'verbose_name': 'Depot Listen Nachricht',
                'verbose_name_plural': 'Depot Listen Nachrichten',
            },
        ),
    ]
