# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0013_auto_20161002_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abo',
            options={'permissions': (('can_filter_abos', 'Benutzer kann Abos filtern'),), 'verbose_name': 'Abo', 'verbose_name_plural': 'Abos'},
        ),
        migrations.AlterModelOptions(
            name='loco',
            options={'permissions': (('can_filter_locos', 'Benutzer kann locos filtern'),), 'verbose_name': 'Loco', 'verbose_name_plural': 'Locos'},
        ),
        migrations.AlterModelOptions(
            name='specialroles',
            options={'permissions': (('is_operations_group', 'Benutzer ist in der BG'), ('is_book_keeper', 'Benutzer ist Buchhalter'), ('can_send_mails', 'Benutzer kann im System Emails versenden'), ('can_use_general_email', 'Benutzer kann General Email Adresse verwenden'))},
        ),
    ]
