# Generated by Django 2.0.8 on 2018-09-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0014_listmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': (('can_filter_subscriptions', 'Benutzer kann Abo filtern'),), 'verbose_name': 'Abo', 'verbose_name_plural': 'Abos'},
        ),
        migrations.AddField(
            model_name='depot',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Kapazität'),
        ),
        migrations.AddField(
            model_name='subscriptionsize',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Sichtbar'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='required_core_assignments',
            field=models.PositiveIntegerField(default=0, verbose_name='Anz benötigter Kern Arbeitseinsätze'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='trial',
            field=models.BooleanField(default=False, verbose_name='ProbeAbo'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='trial_days',
            field=models.IntegerField(default=0, verbose_name='ProbeAbo Dauer in Tagen'),
        ),
        migrations.AlterField(
            model_name='job',
            name='multiplier',
            field=models.PositiveIntegerField(default=1, verbose_name='Arbeitseinsatz vielfaches'),
        ),
        migrations.AlterField(
            model_name='subscriptionsize',
            name='units',
            field=models.FloatField(unique=True, verbose_name='Einheiten'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.IntegerField(verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='shares',
            field=models.PositiveIntegerField(default=0, verbose_name='Anz benötigter Anteilsscheine'),
        ),
    ]
