# Generated by Django 2.2.4 on 2019-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0017_auto_20190625_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enddatum'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='share',
            name='sent_back',
            field=models.BooleanField(default=False, verbose_name='Zurückgesandt'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cancelation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kündigüngsdatum'),
        ),
    ]
