# Generated by Django 2.2.6 on 2019-11-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0018_auto_20191019_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_filter_members', 'Benutzer kann Mitglieder filtern'), ('notified_on_member_creation', 'Wird bei Mitglied Erstellung informiert'), ('notified_on_member_cancellation', 'Wird bei Mitglied Kündigung informiert')], 'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'permissions': [('notified_on_share_creation', 'Wird bei Anteilschein Erstellung informiert'), ('notified_on_share_cancellation', 'Wird bei Anteilschein Kündigung informiert')], 'verbose_name': 'Anteilschein', 'verbose_name_plural': 'Anteilscheine'},
        ),
        migrations.AlterModelOptions(
            name='specialroles',
            options={'permissions': (('is_operations_group', 'Benutzer ist in der BG'), ('is_book_keeper', 'Benutzer ist Buchhalter'), ('can_send_mails', 'Benutzer kann im System Emails versenden'), ('can_use_general_email', 'Benutzer kann General Email Adresse verwenden'))},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('can_filter_subscriptions', 'Benutzer kann Abo filtern'), ('notified_on_subscription_creation', 'Wird bei Abo Erstellung informiert'), ('notified_on_subscription_cancellation', 'Wird bei Abo Kündigung informiert')], 'verbose_name': 'Abo', 'verbose_name_plural': 'Abos'},
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
