# Generated by Django 3.0.1 on 2020-01-12 19:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0019_auto_20191127_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasubscriptiontype',
            name='depot_list',
            field=models.BooleanField(default=True, verbose_name='Sichtbar auf Depotliste'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Sortier-Code'),
        ),
    ]
