# Generated by Django 3.0.1 on 2020-01-23 09:44

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0019_auto_20191127_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasubscriptioncategory',
            name='depot_list',
            field=models.BooleanField(default=True, verbose_name='Sichtbar auf Depotliste'),
        ),
        migrations.AddField(
            model_name='extrasubscriptiontype',
            name='depot_list',
            field=models.BooleanField(default=True, verbose_name='Sichtbar auf Depotliste'),
        ),
        migrations.AddField(
            model_name='job',
            name='infinite_slots',
            field=models.BooleanField(default=False, verbose_name='Unendlich Plaetze'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Sichtbar'),
        ),
        migrations.AddField(
            model_name='recuringjob',
            name='additional_description',
            field=models.TextField(default='', max_length=1000, verbose_name='Zusätzliche Beschreibung'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Sortier-Code'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Plaetze'),
        ),
    ]
