# Generated by Django 3.0.2 on 2020-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0020_auto_20200123_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfsst',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
