# Generated by Django 3.0.5 on 2020-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0021_duration_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='default_duration',
            field=models.PositiveIntegerField(help_text='Standard-Dauer für diese Jobart', verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(help_text='Eindeutiger Name des Einsatzes', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='default_duration',
            field=models.PositiveIntegerField(help_text='Standard-Dauer für diese Jobart', verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='name',
            field=models.CharField(help_text='Eindeutiger Name des Einsatzes', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recuringjob',
            name='duration_override',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Wenn nicht angegeben, wird die Standard-Dauer von der Jobart übernommen.', null=True, verbose_name='Dauer in Stunden (Überschreibend)'),
        ),
    ]
