# Generated by Django 3.0.5 on 2020-04-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0023_migrate_sub_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsst',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='tsst',
            name='type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='cancelation_date',
            new_name='cancellation_date',
        ),
        migrations.RemoveField(
            model_name='extrasubscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='extrasubscription',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='future_types',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='types',
        ),
        migrations.AlterField(
            model_name='subscriptionpart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_parts', to='juntagrico.SubscriptionType', verbose_name='Abo-Typ'),
        ),
        migrations.DeleteModel(
            name='TFSST',
        ),
        migrations.DeleteModel(
            name='TSST',
        ),
    ]
