# Generated by Django 3.0.8 on 2020-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0024_auto_20200415_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='duration',
            new_name='default_duration'
        ),
        migrations.RenameField(
            model_name='onetimejob',
            old_name='duration',
            new_name='default_duration'
        ),
        migrations.AddField(
            model_name='recuringjob',
            name='duration_override',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Wenn nicht angegeben, wird die Standard-Dauer von der Jobart übernommen.', null=True, verbose_name='Dauer in Stunden (Überschreibend)'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(help_text='Eindeutiger Name des Einsatzes', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='name',
            field=models.CharField(help_text='Eindeutiger Name des Einsatzes', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
