# Generated by Django 3.0.8 on 2020-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0025_auto_20200708_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasubscription',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungsdatum'),
        ),
        migrations.AlterField(
            model_name='extrasubscription',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kündigungsdatum'),
        ),
        migrations.AlterField(
            model_name='extrasubscription',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivierungsdatum'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='default_duration',
            field=models.PositiveIntegerField(help_text='Standard-Dauer für diese Jobart', verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='onetimejob',
            name='default_duration',
            field=models.PositiveIntegerField(help_text='Standard-Dauer für diese Jobart', verbose_name='Dauer in Stunden'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kündigungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivierungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionpart',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Aktivierungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionpart',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kündigungsdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionpart',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivierungsdatum'),
        ),
    ]
