# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0026_auto_20161208_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Name')),
                ('long_name', models.CharField(max_length=100, unique=True, verbose_name=b'Langer Name')),
                ('size', models.PositiveIntegerField(unique=True, verbose_name=b'Gr\xc3\xb6sse')),
                ('shares', models.PositiveIntegerField(verbose_name=b'Anz ben\xc3\xb6tigter Anteilsscheine')),
                ('depot_list', models.BooleanField(default=True, verbose_name=b'Sichtbar auf Depotliste')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name=b'Beschreibung')),
            ],
            options={
                'verbose_name': 'Abo Gr\xf6sse',
                'verbose_name_plural': 'Abo Gr\xf6ssen',
            },
        ),
    ]
