# Generated by Django 3.0.8 on 2020-08-03 09:19

import django.db.models.deletion
from django.db import migrations, models

import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0027_auto_20200921_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Beitrittsdatum')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.Member')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.Subscription')),
            ],
            options={
                'verbose_name': 'Abo-Mitgliedschaft',
                'verbose_name_plural': 'Abo-Mitgliedschaften',
                'unique_together': {('member', 'subscription')},
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.AddField(
            model_name='share',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Erzeugt am'),
        ),
        migrations.AlterField(
            model_name='share',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Erzeugt am'),
        ),
    ]
