# Generated by Django 3.1.1 on 2020-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0029_auto_20200810_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='cancelation_date',
            new_name='cancellation_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='member',
            name='future_subscription',
        ),
        migrations.RemoveField(
            model_name='member',
            name='inactive',
        ),
        migrations.RemoveField(
            model_name='member',
            name='old_subscriptions',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, help_text='Voraususchtliches Datum an dem die Mitgliedschaft enden wird. Hat keinen Effekt im System', null=True, verbose_name='Enddatum'),
        ),
    ]
