# Generated by Django 3.1.5 on 2021-01-17 19:01

from django.db import migrations
from juntagrico.entity.member import Member


def fix_user_field(apps, schema_editor):
    # In case there are legacy members with user field None, trigger
    # standard pre-save option to create corresponding users
    for m in Member.objects.all():
        if getattr(m, 'user', None) is None:
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0031_pre_1_4'),
    ]

    operations = [
        migrations.RunPython(fix_user_field),
    ]
