# Generated by Django 3.1.5 on 2021-01-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraSubBillingPeriod',
            new_name='BillingPeriod',
        ),
        migrations.AlterModelOptions(
            name='billingperiod',
            options={'verbose_name': 'Verechnungsperdiode', 'verbose_name_plural': 'Verechnungsperdioden'},
        ),
        migrations.RemoveField(
            model_name='billingperiod',
            name='type',
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='juntagrico.subscriptionproduct'),
        ),
        migrations.DeleteModel(
            name='ExtraSubscription',
        ),
    ]
