# Generated by Django 3.1.5 on 2021-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='member', to='auth.user'),
        ),
    ]
