# Generated by Django 3.1.5 on 2021-01-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='member', to='auth.user'),
        ),
        migrations.RemoveField(
            model_name='depot',
            name='code',
        ),
        migrations.RenameModel(
            old_name='ExtraSubBillingPeriod',
            new_name='BillingPeriod',
        ),
        migrations.AlterModelOptions(
            name='billingperiod',
            options={'verbose_name': 'Verrechnungsperiode', 'verbose_name_plural': 'Verrechnungsperioden'},
        ),
        migrations.RemoveField(
            model_name='billingperiod',
            name='type',
        ),
        migrations.RenameField(
            model_name='billingperiod',
            old_name='type2',
            new_name='type'
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='juntagrico.subscriptiontype'),
        ),
        migrations.DeleteModel(
            name='ExtraSubscription',
        ),
        migrations.RemoveField(
            model_name='extrasubscriptiontype',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExtraSubscriptionCategory',
        ),
        migrations.DeleteModel(
            name='ExtraSubscriptionType',
        ),
    ]
