# Generated by Django 3.2 on 2021-11-16 07:59

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0034_auto_20210415_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('latitude',
                 models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=100, null=True,
                                     verbose_name='Breitengrad')),
                ('longitude',
                 models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=100, null=True,
                                     verbose_name='Längengrad')),
                ('addr_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Strasse & Nr.')),
                ('addr_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ')),
                ('addr_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ort')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Beschreibung')),
                ('visible', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
                'ordering': ['sort_order'],
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='location2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.location',
                                    verbose_name='Ort', null=True),
        ),
        migrations.AddField(
            model_name='onetimejob',
            name='location2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.location',
                                    verbose_name='Ort', null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='location2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.location', null=True),
        ),
    ]
