# Generated by Django 3.2.8 on 2021-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0034_auto_20210415_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Beschreibung'),
        ),
    ]
