# Generated by Django 3.2.8 on 2021-11-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0034_auto_20210415_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preis'),
        ),
    ]
