# Generated by Django 3.2 on 2021-11-16 08:00

from django.db import migrations, utils, transaction


def lowercase_emails(apps, schema_editor):
    Member = apps.get_model('juntagrico', 'Member')
    for member in Member.objects.all():
        member.email = member.email.lower()
        try:
            with transaction.atomic():
                member.save()
        except utils.IntegrityError:
            print('\nWARNING: Duplicate email address must be fixed manually: ', member.email)


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0035_pre_1_5'),
    ]

    operations = [
        migrations.RunPython(lowercase_emails),
    ]
