# Generated by Django 4.0.1 on 2022-02-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0037_post_1_5'),
    ]

    operations = [
    ]
