# Generated by Django 4.0.1 on 2022-02-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0037_post_1_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmembership',
            name='join_date',
            field=models.DateField(blank=True, help_text='Erster Tag an dem Abo bezogen wird', null=True, verbose_name='Beitrittsdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionmembership',
            name='leave_date',
            field=models.DateField(blank=True, help_text='Letzter Tag an dem Abo bezogen wird', null=True, verbose_name='Austrittsdatum'),
        ),
        migrations.AlterField(
            model_name='subscriptionmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.member', verbose_name='Mitglied'),
        ),
        migrations.AlterField(
            model_name='subscriptionmembership',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.subscription', verbose_name='Abo'),
        ),
    ]
