# Generated by Django 4.0.1 on 2022-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0038_contact_remove_activityarea_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sort_order',
            field=models.BigIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
    ]
