# Generated by Django 4.0.1 on 2022-02-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0038_pre_1_6'),
    ]

    operations = [
    ]
