# Generated by Django 4.0.1 on 2022-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0039_data_1_6'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionsize',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsize',
            constraint=models.UniqueConstraint(fields=('name', 'product'), name='unique_name_product'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsize',
            constraint=models.UniqueConstraint(fields=('units', 'product'), name='unique_units_product'),
        ),
    ]
