# Generated by Django 4.0.10 on 2023-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0040_post_1_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allow_unsubscribe',
            field=models.BooleanField(default=False, verbose_name='Abmelden erlauben'),
        ),
    ]
