# Generated by Django 4.2.10 on 2024-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0041_depot_fee_depotsubscriptiontypecondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allow_unsubscribe',
            field=models.BooleanField(default=False, verbose_name='Abmelden erlauben'),
        ),
    ]
