# Generated by Django 4.2.10 on 2024-07-06 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juntagrico", "0041_depot_fee_depotsubscriptiontypecondition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="pickup_duration",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Abholzeitfenster in Stunden",
            ),
        ),
        migrations.AddField(
            model_name="depot",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Abholzeit"),
        ),
        migrations.AlterField(
            model_name="depot",
            name="weekday",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Montag"),
                    (2, "Dienstag"),
                    (3, "Mittwoch"),
                    (4, "Donnerstag"),
                    (5, "Freitag"),
                    (6, "Samstag"),
                    (7, "Sonntag"),
                ],
                verbose_name="Abholtag",
            ),
        ),
    ]
