# Generated by Django 4.2.18 on 2025-04-24 14:31

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0041_1_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_modify_area', models.BooleanField(default=True, verbose_name='Kann Beschreibung ändern')),
                ('can_view_member', models.BooleanField(default=True, verbose_name='Kann Mitglieder sehen')),
                ('can_contact_member', models.BooleanField(default=True, verbose_name='Kann Mitglieder kontaktieren')),
                ('can_modify_jobs', models.BooleanField(default=True, verbose_name='Kann Jobs verwalten')),
                ('can_modify_assignments', models.BooleanField(default=True, verbose_name='Kann Einsatzanmeldungen verwalten')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.activityarea')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.member')),
            ],
            options={
                'verbose_name': 'Koordinator',
                'verbose_name_plural': 'Koordinatoren',
                'ordering': ['sort_order'],
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.AddField(
            model_name='activityarea',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinated_areas', through='juntagrico.AreaCoordinator', to='juntagrico.member', verbose_name='Koordinatoren'),
        ),
        migrations.AddConstraint(
            model_name='areacoordinator',
            constraint=models.UniqueConstraint(fields=('area', 'member'), name='unique_area_member'),
        ),
    ]
