# Generated by Django 4.2.18 on 2025-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0041_1_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='required_assignments',
            field=models.FloatField(verbose_name='Anz benötigter Arbeitseinsätze'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='required_core_assignments',
            field=models.FloatField(default=0, verbose_name='Anz benötigter Kern Arbeitseinsätze'),
        ),
    ]
