# Generated by Django 4.2.16 on 2024-11-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0042_depot_pickup_duration_depot_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='members',
            field=models.ManyToManyField(related_name='jobs', through='juntagrico.Assignment', to='juntagrico.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='subscriptions',
            field=models.ManyToManyField(related_name='members', through='juntagrico.SubscriptionMembership', to='juntagrico.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='types',
            field=models.ManyToManyField(related_name='subscriptions', through='juntagrico.SubscriptionPart', to='juntagrico.subscriptiontype'),
        ),
    ]
