# Generated by Django 4.2.18 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0042_areacoordinator_activityarea_coordinators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinator',
            name='can_remove_member',
            field=models.BooleanField(default=True, verbose_name='Kann Mitglieder entfernen'),
        ),
    ]
