# Generated by Django 4.2.16 on 2024-12-03 21:58

import django.db.models.deletion
from django.db import migrations, models

import juntagrico.entity.share


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0042_depot_pickup_duration_depot_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscriptions',
            field=models.ManyToManyField(related_name='members', through='juntagrico.SubscriptionMembership', to='juntagrico.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='types',
            field=models.ManyToManyField(related_name='subscriptions', through='juntagrico.SubscriptionPart', to='juntagrico.subscriptiontype'),
        ),
        migrations.AlterField(
            model_name='share',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.member'),
        ),
        migrations.AlterField(
            model_name='share',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=juntagrico.entity.share.share_value_default, max_digits=8, verbose_name='Wert'),
        ),
    ]
