# Generated by Django 4.2.17 on 2024-12-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0043_member_subscriptions_subscription_types_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionmembership',
            unique_together=set(),
        ),
    ]
