# Generated by Django 4.2.16 on 2024-11-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0044_alter_subscriptionmembership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='members',
            field=models.ManyToManyField(related_name='jobs', through='juntagrico.Assignment', to='juntagrico.member'),
        ),
    ]
