# Generated by Django 4.2.17 on 2024-12-23 22:51

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0045_job_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionSize',
            new_name='SubscriptionBundle',
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Abo-Kategorie',
                'verbose_name_plural': 'Abo-Kategorie',
                'ordering': ['sort_order'],
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('units', models.FloatField(default=1.0, verbose_name='Einheiten')),
                ('show_on_depot_list', models.BooleanField(default=True, verbose_name='Sichtbar auf Depotliste')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='juntagrico.subscriptionproduct', verbose_name='Produkt')),
            ],
            options={
                'abstract': False, 'verbose_name': 'Produktgrösse', 'verbose_name_plural': 'Produktgrössen'
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.RemoveConstraint(
            model_name='delivery',
            name='unique_delivery',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='subscription_size',
            new_name='subscription_bundle',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='size',
            new_name='bundle',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='Ist Zusatzabo'),
        ),
        migrations.AddField(
            model_name='subscriptionbundle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Wenn leer, kann dieses Paket nicht bestellt werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='juntagrico.subscriptioncategory', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='SubscriptionBundleProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.subscriptionbundle')),
                ('product_size',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.productsize')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionbundle',
            name='product_sizes',
            field=models.ManyToManyField(related_name='bundles', through='juntagrico.SubscriptionBundleProductSize',
                                         to='juntagrico.productsize', verbose_name='Produktgrössen'),
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_name_product',
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('name', 'product'), name='unique_name_product'),
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_units_product',
        ),
        migrations.AddConstraint(
            model_name='subscriptionbundle',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('delivery_date', 'tour', 'subscription_bundle'),
                                               name='unique_delivery'),
        ),
    ]
