# Generated by Django 4.2.17 on 2024-12-23 22:51

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity

# TODO: Do data migration
class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0045_job_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionSize',
            new_name='SubscriptionBundle',
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Abo-Kategorie',
                'verbose_name_plural': 'Abo-Kategorie',
                'ordering': ['sort_order'],
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField(default=1.0, verbose_name='Einheiten')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_name_product',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_units_product',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='depot_list',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='units',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='is_extra',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='Ist Zusatzabo'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='juntagrico.subscriptionbundle', verbose_name='Grösse'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='juntagrico.subscriptionproduct', verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='subscriptionbundle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Wenn leer, kann dieses Paket nicht bestellt werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='juntagrico.subscriptioncategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='subscriptionbundle',
            name='products',
            field=models.ManyToManyField(related_name='sizes', through='juntagrico.SubscriptionItem', to='juntagrico.subscriptionproduct', verbose_name='Produkte'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionbundle',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
    ]
