# Generated by Django 4.2.18 on 2025-01-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0045_job_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='signup_comment',
            field=models.TextField(blank=True, default='', help_text='Kommentar, den das Mitglied bei der Anmeldung hinterlassen hat', verbose_name='Kommentar bei Anmeldung'),
        ),
    ]
