# Generated by Django 4.2.17 on 2024-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0046_rename_subscriptionsize_subscriptionbundle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delivery',
            name='unique_delivery',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='subscription_size',
            new_name='subscription_bundle',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='size',
            new_name='bundle',
        ),
        migrations.AlterField(
            model_name='subscriptionbundle',
            name='products',
            field=models.ManyToManyField(related_name='bundles', through='juntagrico.SubscriptionItem', to='juntagrico.subscriptionproduct', verbose_name='Produkte'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('delivery_date', 'tour', 'subscription_bundle'), name='unique_delivery'),
        ),
    ]
