# Generated by Django 4.2.23 on 2025-12-10 20:38

from django.db import migrations, models


def set_bundle_sort_order(apps, schema_editor):
    subscription_bundles = apps.get_model('juntagrico', 'SubscriptionBundle')
    for idx, item in enumerate(subscription_bundles.objects.all()):
        item.sort_order = idx + 1
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0047_pre_743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionbundle',
            options={'ordering': ['sort_order'], 'verbose_name': 'Abo-Paket', 'verbose_name_plural': 'Abo-Pakete'},
        ),
        migrations.AddField(
            model_name='subscriptionbundle',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
        migrations.RunPython(set_bundle_sort_order),
    ]
