# Generated by Django 4.2.17 on 2024-12-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0047_data_743'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_name_category',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='depot_list',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='units',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='is_extra',
        ),
    ]
