# Generated by Django 4.2.17 on 2024-12-28 15:53

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0047_data_743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='subscription_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.subscriptionbundle',
                                    verbose_name='Abo-Paket'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types',
                                    to='juntagrico.subscriptionbundle', verbose_name='Paket'),
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionbundle',
            name='unique_name_category',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='depot_list',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='units',
        ),
        migrations.RemoveField(
            model_name='subscriptionbundle',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='is_extra',
        ),
    ]
