# Generated by Django 4.2.18 on 2025-05-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0042_alter_subscriptiontype_required_assignments_and_more'),
        ('juntagrico', '0048_post_743'),
    ]

    operations = [
    ]
