# Generated by Django 5.2.10 on 2026-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0050_post_743'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='weekday',
            field=models.PositiveIntegerField(choices=[(1, 'Montag'), (2, 'Dienstag'), (3, 'Mittwoch'), (4, 'Donnerstag'), (5, 'Freitag'), (6, 'Samstag'), (7, 'Sonntag')], null=True, blank=True, verbose_name='Wochentag'),
        ),
    ]
