# Generated by Django 5.2.11 on 2026-03-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0051_tour_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_filter_members', 'Benutzer kann Konten filtern'), ('notified_on_member_creation', 'Wird bei Konto Erstellung informiert'), ('notified_on_member_cancellation', 'Wird bei Konto Kündigung informiert')], 'verbose_name': 'Konto', 'verbose_name_plural': 'Konten'},
        ),
        migrations.AlterModelOptions(
            name='membercontact',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konten'},
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='requires_membership',
            field=models.BooleanField(default=True, verbose_name='Erfordert Mitgliedschaft'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='areas', to='juntagrico.member', verbose_name='Konten'),
        ),
        migrations.AlterField(
            model_name='areacoordinator',
            name='can_contact_member',
            field=models.BooleanField(default=True, verbose_name='Kann Konten kontaktieren'),
        ),
        migrations.AlterField(
            model_name='areacoordinator',
            name='can_remove_member',
            field=models.BooleanField(default=True, verbose_name='Kann Konten entfernen'),
        ),
        migrations.AlterField(
            model_name='areacoordinator',
            name='can_view_member',
            field=models.BooleanField(default=True, verbose_name='Kann Konten sehen'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.member', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='access_information',
            field=models.TextField(default='', help_text='Nur für Konten des/r Depot sichtbar', verbose_name='Zugangsbeschreibung'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Aufpreis für Konto', max_digits=9, verbose_name='Aufpreis'),
        ),
        migrations.AlterField(
            model_name='depotcoordinator',
            name='can_contact_member',
            field=models.BooleanField(default=True, verbose_name='Kann Konten kontaktieren'),
        ),
        migrations.AlterField(
            model_name='depotcoordinator',
            name='can_view_member',
            field=models.BooleanField(default=True, verbose_name='Kann Konten sehen'),
        ),
        migrations.AlterField(
            model_name='depotsubscriptiontypecondition',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Aufpreis für Konto', max_digits=9, verbose_name='Aufpreis'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, help_text='Gewünschtes Löschdatum. Hat keinen Effekt im System', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, help_text='Notizen für Administration. Nicht sichtbar für Konto', verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico.member', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='share',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notizen für Administration. Nicht sichtbar für Konto', verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Notizen für Administration. Nicht sichtbar für Konto', verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='subscriptionmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.member', verbose_name='Konto'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Erstellungsdatum')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Aktivierungsdatum')),
                ('cancellation_date', models.DateField(blank=True, null=True, verbose_name='Kündigungsdatum')),
                ('deactivation_date', models.DateField(blank=True, null=True, verbose_name='Deaktivierungsdatum')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Mitgliedschaftsnummer')),
                ('notes', models.TextField(blank=True, default='', help_text='Notizen für Administration. Nicht sichtbar für Mitglied', verbose_name='Notizen')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='juntagrico.member')),
            ],
            options={
                'verbose_name': 'Mitgliedschaft',
                'verbose_name_plural': 'Mitgliedschaften',
                'permissions': [('notified_on_membership_creation', 'Wird bei Mitgliedschaft Erstellung informiert'), ('notified_on_membership_cancellation', 'Wird bei Mitgliedschaft Kündigung informiert')],
            },
        ),
    ]
