# Generated by Django 5.2.11 on 2026-05-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0053_data_580'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cancellation_comment',
            field=models.TextField(blank=True, default='', help_text='Kommentar, den das Mitglied bei der Kündigung hinterlassen hat', verbose_name='Kommentar bei Abmeldung'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='nickname',
            field=models.CharField(blank=True, help_text='Ersetzt die MitabonnentInnen auf der Depot-Liste.', max_length=30, verbose_name='Spitzname'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='primary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_primary', to='juntagrico.member', verbose_name='Verwalter:in'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='trial_days',
            field=models.IntegerField(default=0, verbose_name='Probedauer in Tagen'),
        ),
    ]
