# Generated by Django 5.2.11 on 2026-03-21 23:11

import django.db.models.deletion
import juntagrico.entity
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0053_data_580'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('addr_street', models.CharField(max_length=100, verbose_name='Strasse')),
                ('addr_zipcode', models.CharField(max_length=10, verbose_name='PLZ')),
                ('addr_location', models.CharField(max_length=50, verbose_name='Ort')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefonnr')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile')),
                ('email', juntagrico.entity.LowercaseEmailField(max_length=254)),
                ('shares', models.PositiveIntegerField(default=0, verbose_name='Anteilscheine')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='juntagrico.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
