# Generated by Django 5.2.11 on 2026-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0054_member_cancellation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Anz benötigter Anteilscheine'),
        ),
    ]
