# Generated by Django 5.2.11 on 2026-07-20 22:20

import django.db.models.deletion
import juntagrico.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0054_member_cancellation_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('can_edit_past_jobs', 'kann vergangene Jobs editieren'), ('manage_job_messages', 'kann alle Mitteilungen zu Einsätzen sehen und verwalten')), 'verbose_name': 'AbstractJob', 'verbose_name_plural': 'AbstractJobs'},
        ),
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False, help_text='Sichtbar für alle Konten', verbose_name='Sichtbar für alle')),
                ('message', models.TextField(verbose_name='Mitteilung')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_messages', to='juntagrico.member', verbose_name='Konto')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='juntagrico.job')),
            ],
            options={
                'verbose_name': 'Einsatzmitteilung',
                'verbose_name_plural': 'Einsatzmitteilungen',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
