# Generated by Django 5.2.11 on 2026-07-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0054_member_cancellation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='count_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juntagrico.job'),
        ),
    ]
