# Generated by Django 5.2.11 on 2026-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0056_alter_subscriptiontype_shares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialroles',
            options={'default_permissions': (), 'managed': False, 'permissions': (('is_book_keeper', 'Ist Buchhalter'), ('can_send_mails', 'Kann E-Mails versenden'), ('can_email_attachments', 'Kann Anhänge per E-Mail senden'), ('can_use_general_email', 'Kann allgemeine E-Mail-Adresse verwenden'), ('can_use_for_members_email', 'Kann E-Mail-Adresse "for_members" verwenden'), ('can_use_for_subscriptions_email', 'Kann E-Mail-Adresse "for_subscription" verwenden'), ('can_use_for_shares_email', 'Kann E-Mail-Adresse "for_shares" verwenden'), ('can_use_technical_email', 'Kann technische E-Mail-Adresse verwenden'), ('can_email_all_with_share', 'Kann E-Mails an alle mit Anteilschein senden'), ('can_email_all_with_sub', 'Kann E-Mails an alle mit Abo senden'), ('depot_list_notification', 'Wird bei Depot-Listen-Erstellung informiert'), ('can_view_exports', 'Kann Exporte öffnen'), ('can_view_lists', 'Kann Listen öffnen'), ('can_generate_lists', 'Kann Listen erzeugen'))},
        ),
        migrations.AlterField(
            model_name='job',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Teilnehmende werden bei Absage automatisch per E-mail benachrichtigt', verbose_name='abgesagt'),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.DateTimeField(help_text='Teilnehmende werden bei Änderung automatisch per E-mail benachrichtigt', verbose_name='Zeitpunkt'),
        ),
    ]
