# Generated by Django 5.2.11 on 2026-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0057_alter_specialroles_options_alter_job_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='identifier',
            field=models.CharField(blank=True, help_text='Eindeutige Kennzeichnung (optional)', max_length=30, null=True, unique=True, verbose_name='Kennzeichnung'),
        ),
    ]
