# Generated by Django 5.2.11 on 2026-08-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0058_subscription_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billable',
            name='polymorphic_ctype',
        ),
    ]
