# Generated by Django 5.2.11 on 2026-09-06 11:06

import django.db.models.deletion
import juntagrico.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0058_subscription_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Verwende negative Beträge für Rabatte.', max_digits=9, verbose_name='Betrag')),
                ('date', models.DateField(verbose_name='Verrechnungsdatum')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='juntagrico.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
