# Generated by Django 5.2.11 on 2026-09-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0059_subscriptionsurcharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialroles',
            options={'default_permissions': (), 'managed': False, 'permissions': (('is_book_keeper', 'Ist Buchhalter'), ('can_send_mails', 'Kann E-Mails versenden'), ('can_email_attachments', 'Kann Anhänge per E-Mail senden'), ('can_use_general_email', 'Kann allgemeine E-Mail-Adresse verwenden'), ('can_use_for_members_email', 'Kann E-Mail-Adresse "for_members" verwenden'), ('can_use_for_subscriptions_email', 'Kann E-Mail-Adresse "for_subscription" verwenden'), ('can_use_for_shares_email', 'Kann E-Mail-Adresse "for_shares" verwenden'), ('can_use_technical_email', 'Kann technische E-Mail-Adresse verwenden'), ('can_email_all_with_membership', 'Kann E-Mails an alle mit Mitgliedschaft senden'), ('can_email_all_with_share', 'Kann E-Mails an alle mit Anteilschein senden'), ('can_email_all_with_sub', 'Kann E-Mails an alle mit Abo senden'), ('depot_list_notification', 'Wird bei Depot-Listen-Erstellung informiert'), ('can_view_exports', 'Kann Exporte öffnen'), ('can_view_lists', 'Kann Listen öffnen'), ('can_generate_lists', 'Kann Listen erzeugen'))},
        ),
    ]
