# Generated by Django 5.2.11 on 2026-10-01 19:21

import django.db.models.deletion
import juntagrico.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0060_alter_specialroles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='juntagrico.subscription')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='Startdatum muss vor Enddatum liegen.')],
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
