# Generated by Django 5.2.11 on 2026-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0061_subscriptionabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsurcharge',
            name='required_assignments',
            field=models.FloatField(default=0, verbose_name='Anz. benötigter Arbeitseinsätze'),
        ),
        migrations.AddField(
            model_name='subscriptionsurcharge',
            name='required_core_assignments',
            field=models.FloatField(default=0, verbose_name='Anz. benötigter Kern-Arbeitseinsätze'),
        ),
    ]
