# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0004_auto_20160119_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='taetigkeitsbereich',
            name='show_coordinator_phonenumber',
            field=models.BooleanField(default=False, verbose_name=b'Koordinator Tel Nr Ver\xc3\xb6ffentlichen'),
        ),
    ]
