# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0011_auto_20161001_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='boehnli',
            name='core_cache',
            field=models.BooleanField(default=False, verbose_name=b'Kernbereich'),
        ),
    ]
