# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0014_auto_20161019_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteilschein',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='anteilschein',
            name='canceled_date',
        ),
        migrations.RemoveField(
            model_name='anteilschein',
            name='paid',
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='booking_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Eingebucht am'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Gek\xc3\xbcndigt am'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Ausgestellt am'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='payback_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Zur\xc3\xbcckbezahlt am'),
        ),
        migrations.AddField(
            model_name='anteilschein',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Gek\xc3\xbcndigt auf'),
        ),
    ]
