# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0015_auto_20161117_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='abo',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Aktivierungssdatum'),
        ),
        migrations.AddField(
            model_name='abo',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Deaktivierungssdatum'),
        ),
    ]
