# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0025_auto_20161208_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraabo',
            name='tmp_abo_id',
        ),
        migrations.RemoveField(
            model_name='loco',
            name='tmp_abo_id',
        ),
    ]
