# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0027_abosize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abo',
            name='extra_abos_changed',
        ),
    ]
