# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def data_migration(apps, schema_editor):
        Abo = apps.get_model("my_ortoloco", "Abo")
        ExtraAbo = apps.get_model("my_ortoloco", "ExtraAbo")
        ExtraAboType = apps.get_model("my_ortoloco", "ExtraAboType")
       
        for abo in Abo.objects.all():
            for type in ExtraAboType.objects.all():
                futures=abo.extra_abo_set.filter(active=False).filter(type=type)
                currents=abo.extra_abo_set.filter(active=True).filter(type=type)
                if currents.count()>0 and futures.count()>0:
                    for future in futures:
                        future.delete()
            
    dependencies = [
        ('my_ortoloco', '0028_remove_abo_extra_abos_changed'),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
