# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import my_ortoloco.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('my_ortoloco', '0030_auto_20170301_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='abo',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=b'Erstellungsdatum'),
        ),
        migrations.AddField(
            model_name='abo',
            name='start_date',
            field=models.DateField(default=my_ortoloco.helpers.start_of_year, verbose_name=b'Gew\xc3\xbcnschtes Startdatum'),
        ),
    ]
